title: Building a site with Jekyll
description: > # this means to ignore newlines until "baseurl:"
  Jekyll walkthrough for Code4Lib Midwest 2017. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kateefly
github_username:  kateefly

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock